name: scan-missconfig
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  ORG: "khulnasoft"
jobs:
  scan-missconfig:
    name: missconfiguration
    runs-on: ubuntu-22.04
    permissions:
      security-events: write # https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tunnel - misconfiguration artifacts
        uses: khulnasoft/tunnel-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Tunnel - misconfiguration artifacts - sarif.tpl
        uses: khulnasoft/tunnel-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'
          output: 'tunnel-config.sarif'

      - name: Upload Tunnel scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: 'tunnel-config.sarif'
