name: scan-fs
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  ORG: "khulnasoft"
jobs:
  scan-fs:
    name: filesystem
    runs-on: ubuntu-20.04
    permissions:
      security-events: write # https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tunnel - fs
        uses: khulnasoft/tunnel-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Tunnel - file system - sarif
        uses: khulnasoft/tunnel-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'sarif'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          output: 'tunnel-fs.sarif'

      - name: Upload Tunnel scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: 'tunnel-fs.sarif'
